---
layout: default
---

# ¡Hola! Soy [Tu Nombre]

Soy **Data Scientist** con experiencia en distintas etapas de crecimiento profesional:

- **Junior Data Scientist**: Inicié mi carrera desarrollando modelos predictivos básicos, aprendiendo herramientas de análisis de datos y colaborando en proyectos de menor escala.
- **Senior Data Scientist**: Con el tiempo, asumí proyectos más complejos y lideré iniciativas de optimización, extracción de insights y diseño de estrategias basadas en datos.
- **Product Owner**: Mi rol evolucionó hacia la definición de la visión y el roadmap de productos de Data Science, priorizando tareas y maximizando el valor del producto para los stakeholders.
- **Líder Técnico**: Dirigí equipos multidisciplinarios y coordiné soluciones de arquitectura de datos, asegurando la calidad y el cumplimiento de los objetivos técnicos.
- **Doctorado**: Ahora me preparo para iniciar un programa de doctorado, con el objetivo de profundizar en investigación aplicada e innovar en el mundo del análisis de datos y la inteligencia artificial.

## Habilidades

- **Lenguajes de Programación**: Python, R, SQL
- **Herramientas y Frameworks**: TensorFlow, PyTorch, scikit-learn
- **Metodologías**: Scrum, Kanban
- **Data Visualization**: Tableau, Power BI, matplotlib, Plotly

## Proyectos Destacados

1. **Análisis de demanda de productos**  
   - _Resumen_: Desarrollo de un modelo predictivo de ventas con Python y R, reduciendo la sobreproducción en un 15%.

2. **Sistema de recomendación de cursos**  
   - _Resumen_: Creación de un sistema de recomendación personalizada para un cliente educativo, incrementando la retención de usuarios en un 25%.

3. **Automatización de reportes ejecutivos**  
   - _Resumen_: Implementación de scripts en Python para la extracción de datos y elaboración de reportes, ahorrando hasta un 40% de tiempo de análisis semanal.

## Contacto

- **GitHub**: [tu-usuario](https://github.com/tu-usuario)
- **LinkedIn**: [linkedin.com/in/tu-perfil](https://linkedin.com/in/tu-perfil)
- **Email**: [tucorreo@ejemplo.com](mailto:tucorreo@ejemplo.com)

---

> ¡Gracias por visitar mi página! Siempre estoy abierto(a) a nuevas oportunidades de colaboración e investigación.
